listen_addr = ":9000"

table_file_path = "db/table"

# The maximum amount of time between saves to disk.
save_duration = "10s"

# The maximum size of the DB
rows = 100000

# Every row must have a timestamp column. This is the name of that column.
timestamp_column = "at"

dimension_columns = [
  ["name", "string:uint16"],
  ["country", "string:uint8"],
  ["age", "uint8"]
]

metric_columns = [
  ["visits", "uint8"],
  ["clicks", "uint8"],
]
