listen_addr = ":9000"

database_dir = "db"

# Flush to disk at least this frequently.
flush_interval = "10s"

[schema]

# Data is partitioned into time intervals this large.
interval_duration = "1h"

# Every row must have a timestamp column. This is the name of that column.
timestamp_column = ["at", "uint32"]

dimension_columns = [
  ["name", "string:uint16"],
  ["country", "string:uint8"],
  ["age", "uint8"]
]

metric_columns = [
  ["visits", "uint8"],
  ["clicks", "uint8"]
]
